version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev  # Especifica el nuevo Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    tty: true