# Generated by Django 5.1 on 2024-09-08 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceStudent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('attendance', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'attendance_student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthtokenToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'authtoken_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'permissions': [('permiso_especial', 'Descripción del permiso especial')],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BirthParents',
            fields=[
                ('id', models.BigAutoField(db_comment='Unique identifier for birth_parents', primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state_department', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'birth_parents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BirthStudents',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state_department', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'birth_students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('day', models.CharField(blank=True, max_length=50, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(db_comment='Unique identifier for the parents', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_comment='Names of the parent', max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, db_comment='Last names of the parent', max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_comment='Email of the parent', max_length=255, null=True, unique=True)),
                ('phone', models.CharField(blank=True, db_comment='Phone number of the parent including the country calling code', max_length=255, null=True, unique=True)),
                ('address', models.CharField(blank=True, db_comment='Current residential address of the parent', max_length=255, null=True)),
                ('district', models.CharField(blank=True, db_comment='Current district of the parent', max_length=255, null=True)),
                ('city', models.CharField(blank=True, db_comment='Current city of the parent', max_length=255, null=True)),
                ('state_department', models.CharField(blank=True, db_comment='Current state or department of the parent', max_length=255, null=True)),
                ('country', models.CharField(blank=True, db_comment='Current country of the parent', max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, db_comment='Current nationality of the parent', max_length=255, null=True)),
                ('document_type', models.CharField(blank=True, db_comment='Type of national identification document of the parent', max_length=255, null=True)),
                ('document_id', models.CharField(blank=True, db_comment='Identification number of the national identification document of the parent', max_length=255, null=True, unique=True)),
                ('birthdate', models.DateField(blank=True, db_comment='Date of birth of the parent', null=True)),
                ('gender', models.CharField(blank=True, db_comment='Gender of the parent', max_length=50, null=True)),
                ('status', models.IntegerField(blank=True, db_comment='Indicates whether the parent is active or inactive', null=True)),
                ('created_at', models.DateTimeField(blank=True, db_comment='Timestamp of when the parent record was created', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_comment='Timestamp of when the parent record was last updated', null=True)),
            ],
            options={
                'db_table': 'parents',
                'db_table_comment': 'This table store basic information of the parent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'student_class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('document_type', models.CharField(blank=True, max_length=255, null=True)),
                ('document_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VolunteerClass',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'volunteer_class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Volunteers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('org_email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('photo', models.CharField(max_length=255, null=True, unique=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('document_type', models.CharField(blank=True, max_length=255, null=True)),
                ('document_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'volunteers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id_session', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('num_session', models.IntegerField(blank=True, null=True)),
                ('id_class', models.ForeignKey(db_column='id_class', on_delete=django.db.models.deletion.CASCADE, to='api.class')),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
    ]
